{% set name = "byobu" %}
{% set version = "5.130" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://launchpad.net/byobu/trunk/{{ version }}/+download/byobu_{{ version }}.orig.tar.gz
  sha256: 47e414161dda124287b9ec1cf94acc716b49e7428c6ec7efeed181f477e17461
  patches:
    # Ensure we use python in the same conda environment
    - 0001-use-local-python.diff
    # Ensure byobu conda environment is activated
    - 0002-byobu-conda.diff

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - autoconf
    - automake
    - make
  host:
    - coreutils  # [osx]
    - gettext    # [osx]
  run:
    - newt
    - tmux >=1.5
    # GNU Tools
    - coreutils  # [osx]
    - gawk       # [osx]
    - gettext    # [osx]
    - sed        # [osx]

test:
  commands:
    - byobu -c "echo 'Hello conda-forge!'"

    # Tests patch 0001 works
    - unset BYOBU_PYTHON
    - test "$(which python)" = "$(which $(byobu -c 'echo ${BYOBU_PYTHON}'))"

    # Test patch 0002 files
    - test -x ${CONDA_PREFIX}/bin/byobu-enable-conda
    - test -x ${CONDA_PREFIX}/bin/byobu-disable-conda

about:
  home: http://byobu.co
  license: GPL-3
  license_family: GPL
  license_file: COPYING
  summary: 'Byobu is a text-based window manager and terminal multiplexer.'

  description: |
    Byobu was originally designed to provide elegant enhancements to the
    otherwise functional, plain, practical GNU Screen, for the Ubuntu server
    distribution. Byobu now includes an enhanced profiles, convenient
    keybindings, configuration utilities, and toggle-able system status
    notifications for both the GNU Screen window manager and the more modern
    Tmux terminal multiplexer, and works on most Linux, BSD, and Mac
    distributions.
  doc_url: http://byobu.co/documentation.html
  dev_url: http://bazaar.launchpad.net/~kirkland/byobu/trunk/files

extra:
  recipe-maintainers:
    - sodre
