appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: GTu8nEdno8tP4Hp1HvqxMAVI+C2YJ5XKKSdcXOAwKd7+Ji+VRAmscre/0gDW3/UEMktRU1vLWAU6Bw3awFqNEbnWZx7zEUEIFcdk0iF4luOnGfwoM0sjdz7ALhI7XBsbAiulJqhbqwPZQvIGCFsxcfiKGwltFiKVcydxqW4nQMnyCbBHb3plkILirG6Yv04yJCJ4TmYqE6UyRifonW8beH1uiCnmoKbZIzTiuw3x+a25EXLAuHEcTIEvTBervEBF3IPfAZkVqhcJbPBg8PTa1VCL9VhBc58zySOXF8lqqjelyHh1kuuzhmWR44N8fP3jx1GCkCjeY7ploQUQVaCXO+vF8H2ugxn+5sJ7h/crjWbe6eiXNFXBw8CC6B9K+xKb22ogEOr3m4uZWEUOLPUMr+pnR/ThUvx1RfDWLY/13KH8TIzZfveVtBrzKF63lm5rXoH2lv9q1EnIz9aPzo/OST3Kpn0axr+ot6gLjtUcQ4tqsC4Y/xhscXhCriL0W2ImxuGV4P3FyE0jYqPEIocEnQG0RXu9nDaje29pizJUC5Ccdo1SZSSIRBFWdXIaA3+muPhRE5NsCuuC9Us/PwUQI/jt0Z44RyFFjHfeej4uZvYRWBkaYKYOIx7x9vpszSneZ9lwU21EOHSa2sNDicKbJakjqPjS0gFk+AMAW0zqn+k=}
bot:
  automerge: true
conda_forge_output_validation: true
